FROM python:3.11

WORKDIR /app

RUN apt-get update && apt-get install -y \
    musescore \
    xvfb \
    && rm -rf /var/lib/apt/lists/*

COPY ./Backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./Backend .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]